import { createHash } from 'node:crypto';
import { PRODUCTION_ORIGIN } from './site-contract.mjs';

export const DEPLOYMENT_ENVIRONMENTS = Object.freeze(['production', 'preview']);

const BASE_HEADERS = Object.freeze([
  ['Cross-Origin-Opener-Policy', 'same-origin'],
  ['Cross-Origin-Resource-Policy', 'same-origin'],
  ['Permissions-Policy', 'camera=(), geolocation=(), microphone=(), payment=(), usb=()'],
  ['Referrer-Policy', 'no-referrer'],
  ['Strict-Transport-Security', 'max-age=31536000'],
  ['X-Content-Type-Options', 'nosniff'],
  ['X-Frame-Options', 'DENY'],
]);

export function extractInlineScriptHashes(html) {
  const hashes = new Set();
  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi)) {
    const attributes = match[1];
    const body = match[2];
    if (/(?:^|\s)src(?:\s*=|\s|$)/i.test(attributes) || body.length === 0) continue;
    hashes.add(`sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}`);
  }
  return [...hashes].sort();
}

export function buildContentSecurityPolicy(scriptHashes = []) {
  const normalizedHashes = [...new Set(scriptHashes)].sort();
  for (const hash of normalizedHashes) {
    if (!/^sha256-[A-Za-z0-9+/]{43}=$/.test(hash)) {
      throw new Error(`Invalid CSP script hash: ${hash}`);
    }
  }
  const scriptSources = ["'self'", ...normalizedHashes.map((hash) => `'${hash}'`)].join(' ');
  return [
    "default-src 'self'",
    "base-uri 'none'",
    "connect-src 'self'",
    "font-src 'self'",
    "form-action 'none'",
    "frame-ancestors 'none'",
    "img-src 'self'",
    "manifest-src 'self'",
    "media-src 'self'",
    "object-src 'none'",
    `script-src ${scriptSources}`,
    "style-src 'self' 'unsafe-inline'",
    "worker-src 'self'",
  ].join('; ');
}

export function assertDeploymentEnvironment(environment) {
  if (!DEPLOYMENT_ENVIRONMENTS.includes(environment)) {
    throw new Error(`Deployment environment must be one of: ${DEPLOYMENT_ENVIRONMENTS.join(', ')}`);
  }
}

export function buildHeaders(environment, { scriptHashes = [] } = {}) {
  assertDeploymentEnvironment(environment);

  const lines = [
    '# Generated by scripts/prepare-deploy.mjs. Do not edit build output.',
    '/*',
    `  Content-Security-Policy: ${buildContentSecurityPolicy(scriptHashes)}`,
  ];
  for (const [name, value] of BASE_HEADERS) lines.push(`  ${name}: ${value}`);

  if (environment === 'preview') {
    lines.push('  X-Robots-Tag: noindex, nofollow, noarchive');
  }

  lines.push(
    '',
    '# Even production assets must not index from versioned workers.dev URLs.',
    'https://:deployment.:account.workers.dev/*',
    '  X-Robots-Tag: noindex, nofollow, noarchive',
    '',
    '/_astro/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '',
    '/*.html',
    '  Cache-Control: public, max-age=0, must-revalidate',
    '',
    '/robots.txt',
    '  Cache-Control: public, max-age=300, must-revalidate',
    '',
  );

  return `${lines.join('\n')}\n`;
}

export function buildRobots(environment) {
  assertDeploymentEnvironment(environment);

  if (environment === 'preview') {
    return 'User-agent: *\nDisallow: /\n';
  }

  return ['User-agent: *', 'Allow: /', `Sitemap: ${PRODUCTION_ORIGIN}/sitemap-index.xml`, ''].join(
    '\n',
  );
}

export function inferDeploymentEnvironment(env = process.env) {
  const explicit = env.SITE_DEPLOYMENT_ENV?.trim().toLowerCase();
  if (explicit) {
    assertDeploymentEnvironment(explicit);
    return explicit;
  }

  const branch =
    env.WORKERS_CI_BRANCH ??
    env.GITHUB_HEAD_REF ??
    env.GITHUB_REF_NAME ??
    env.CF_PAGES_BRANCH ??
    '';

  return branch === 'main' ? 'production' : 'preview';
}
